"""Bounded durable storage primitives for selection publication."""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import tempfile
from typing import Any, Iterator


try:
    import fcntl
except ImportError:  # pragma: no cover - POSIX is the production path.
    fcntl = None  # type: ignore[assignment]


TRANSACTION_ID = re.compile(r"^selection-[0-9a-f]{64}$")
SHA256 = re.compile(r"^[0-9a-f]{64}$")


def _canonical_json(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        + "\n"
    ).encode("utf-8")


def _display_json(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _bounded_payload(payload: bytes, max_bytes: int, label: str) -> bytes:
    """Reject generated bytes before any store path or directory is touched."""

    if len(payload) > max_bytes:
        raise ValueError(f"{label} exceeds {max_bytes // 1024} KiB")
    return payload


def _sha256_file(path: Path) -> str | None:
    if not path.is_file() or path.is_symlink():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _bounded_file_sha256(
    path: Path, expected_size: int, label: str
) -> str | None:
    """Hash one exact-size regular leaf without following a leaf symlink."""

    try:
        before = path.lstat()
    except FileNotFoundError:
        return None
    if (
        not stat.S_ISREG(before.st_mode)
        or before.st_size != expected_size
        or expected_size < 0
    ):
        raise ValueError(f"{label} conflicts with immutable transaction evidence")
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_CLOEXEC", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as exc:
        raise ValueError(
            f"{label} conflicts with immutable transaction evidence"
        ) from exc
    try:
        opened = os.fstat(descriptor)
        if (
            not stat.S_ISREG(opened.st_mode)
            or (opened.st_dev, opened.st_ino, opened.st_size)
            != (before.st_dev, before.st_ino, expected_size)
        ):
            raise ValueError(
                f"{label} conflicts with immutable transaction evidence"
            )
        digest = hashlib.sha256()
        total = 0
        while total <= expected_size:
            chunk = os.read(descriptor, min(1024 * 1024, expected_size + 1 - total))
            if not chunk:
                break
            total += len(chunk)
            digest.update(chunk)
        after = os.fstat(descriptor)
        try:
            current = path.lstat()
        except OSError as exc:
            raise ValueError(
                f"{label} conflicts with immutable transaction evidence"
            ) from exc
        if (
            total != expected_size
            or _file_signature(opened) != _file_signature(after)
            or (current.st_dev, current.st_ino) != (opened.st_dev, opened.st_ino)
        ):
            raise ValueError(
                f"{label} conflicts with immutable transaction evidence"
            )
        return digest.hexdigest()
    finally:
        os.close(descriptor)


def _file_signature(value: os.stat_result) -> tuple[int, int, int, int, int, int]:
    return (
        value.st_dev,
        value.st_ino,
        value.st_mode,
        value.st_size,
        value.st_mtime_ns,
        value.st_ctime_ns,
    )


def _fsync_dir(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _atomic_write(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_value = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_value)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        _fsync_dir(path.parent)
    finally:
        temporary.unlink(missing_ok=True)


def _write_once(path: Path, payload: bytes, label: str) -> str:
    digest = _sha256_bytes(payload)
    if path.exists() or path.is_symlink():
        if _bounded_file_sha256(path, len(payload), label) != digest:
            raise ValueError(f"{label} conflicts with immutable transaction evidence")
        return digest
    _atomic_write(path, payload)
    if _bounded_file_sha256(path, len(payload), label) != digest:
        raise ValueError(f"{label} failed post-write verification")
    return digest


def _safe_directory(path: Path, label: str) -> None:
    if path.is_symlink():
        raise ValueError(f"{label} cannot be a symlink")
    if path.exists() and not path.is_dir():
        raise ValueError(f"{label} must be a directory")


def _safe_regular_file(path: Path, label: str) -> None:
    if path.is_symlink():
        raise ValueError(f"{label} cannot be a symlink")
    if path.exists() and not stat.S_ISREG(path.lstat().st_mode):
        raise ValueError(f"{label} must be a regular file or absent")


def _store_root(root: Path) -> Path:
    root = root.resolve(strict=True)
    task_root = root / ".task"
    store = task_root / "selection_publication"
    _safe_directory(task_root, "selection-publication .task root")
    _safe_directory(store, "selection-publication store root")
    try:
        store.resolve(strict=False).relative_to(root)
    except ValueError as exc:
        raise ValueError("selection-publication store escapes the workspace") from exc
    return store


def _safe_store_directory(root: Path, relative_parts: tuple[str, ...]) -> Path:
    current = _store_root(root)
    for part in relative_parts:
        current /= part
        _safe_directory(current, "selection-publication store component")
    return current


def _prepare_path(root: Path, transaction_id: str) -> Path:
    if not TRANSACTION_ID.fullmatch(transaction_id):
        raise ValueError("invalid selection-publication transaction id")
    directory = _safe_store_directory(root, ("transactions", transaction_id))
    path = directory / "prepare.json"
    _safe_regular_file(path, "selection-publication prepare journal")
    return path


def _transactions_root(root: Path) -> Path:
    return _safe_store_directory(root, ("transactions",))


def _receipt_path(root: Path, transaction_id: str) -> Path:
    if not TRANSACTION_ID.fullmatch(transaction_id):
        raise ValueError("invalid selection-publication transaction id")
    directory = _safe_store_directory(root, ("receipts",))
    path = directory / f"{transaction_id}.json"
    _safe_regular_file(path, "selection-publication receipt")
    return path


def _receipts_root(root: Path) -> Path:
    return _safe_store_directory(root, ("receipts",))


def _blob_path(root: Path, digest: str) -> Path:
    if not re.fullmatch(r"[0-9a-f]{64}", digest):
        raise ValueError("invalid selection-publication blob digest")
    directory = _safe_store_directory(root, ("blobs", "sha256"))
    path = directory / digest
    _safe_regular_file(path, "selection-publication task blob")
    return path


def _state_path(root: Path) -> Path:
    path = _store_root(root) / "state.json"
    _safe_regular_file(path, "selection-publication compact state")
    return path


def _intent_index_path(root: Path, digest: str, name: str) -> Path:
    """Return one immutable O(1) intent lookup path.

    The digest is a directory component rather than caller-controlled path text,
    and both the directory chain and leaf retain the store's symlink guards.
    """

    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selection-publication intent digest")
    if name not in {"prepare", "commit"}:
        raise ValueError("invalid selection-publication intent index kind")
    directory = _safe_store_directory(root, ("intents", "sha256", digest))
    path = directory / f"{name}.json"
    _safe_regular_file(path, f"selection-publication intent {name} index")
    return path


def _successor_bundle_path(root: Path, digest: str) -> Path:
    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selected-successor bundle digest")
    directory = _safe_store_directory(
        root, ("successor_bundles", "sha256")
    )
    path = directory / f"{digest}.json"
    _safe_regular_file(path, "selected-successor bundle")
    return path


def _successor_prepare_index_path(root: Path, digest: str) -> Path:
    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selected-successor prepare-input digest")
    directory = _safe_store_directory(
        root, ("successor_prepare_indexes", "sha256")
    )
    path = directory / f"{digest}.json"
    _safe_regular_file(path, "selected-successor prepare-input index")
    return path


def _successor_gate_path(root: Path, digest: str) -> Path:
    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selected-successor authority-gate digest")
    directory = _safe_store_directory(
        root, ("successor_authority_gates", "sha256")
    )
    path = directory / f"{digest}.json"
    _safe_regular_file(path, "selected-successor authority gate")
    return path


def _successor_authority_request_context_path(root: Path, digest: str) -> Path:
    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selected-successor request-context digest")
    directory = _safe_store_directory(
        root, ("successor_authority_request_contexts", "sha256")
    )
    path = directory / f"{digest}.json"
    _safe_regular_file(path, "selected-successor authority request context")
    return path


def _successor_authority_evaluation_context_path(root: Path, digest: str) -> Path:
    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selected-successor evaluation-context digest")
    directory = _safe_store_directory(
        root, ("successor_authority_evaluation_contexts", "sha256")
    )
    path = directory / f"{digest}.json"
    _safe_regular_file(path, "selected-successor authority evaluation context")
    return path


def _successor_authority_packet_path(root: Path, digest: str) -> Path:
    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selected-successor authority-packet digest")
    directory = _safe_store_directory(
        root, ("successor_authority_packets", "sha256")
    )
    path = directory / f"{digest}.json"
    _safe_regular_file(path, "selected-successor authority packet")
    return path


def _successor_authority_index_path(root: Path, digest: str) -> Path:
    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selected-successor authority-input digest")
    directory = _safe_store_directory(
        root, ("successor_authority_indexes", "sha256")
    )
    path = directory / f"{digest}.json"
    _safe_regular_file(path, "selected-successor authority-input index")
    return path


def _successor_authority_projection_path(root: Path, digest: str) -> Path:
    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selected-successor authority-projection digest")
    directory = _safe_store_directory(
        root, ("successor_authority_projections", "sha256")
    )
    path = directory / f"{digest}.json"
    _safe_regular_file(path, "selected-successor authority projection")
    return path


def _successor_authority_locator_path(root: Path, digest: str) -> Path:
    if not SHA256.fullmatch(digest):
        raise ValueError("invalid selected-successor authority-locator digest")
    directory = _safe_store_directory(
        root, ("successor_authority_locators", "sha256")
    )
    path = directory / f"{digest}.json"
    _safe_regular_file(path, "selected-successor authority locator")
    return path


def _create_store_directories(root: Path) -> Path:
    store = _store_root(root)
    task_root = root / ".task"
    if not task_root.exists():
        task_root.mkdir()
    _safe_directory(task_root, "selection-publication .task root")
    if not store.exists():
        store.mkdir()
    _safe_directory(store, "selection-publication store root")
    return store


@contextlib.contextmanager
def _lock(root: Path) -> Iterator[None]:
    store = _create_store_directories(root)
    path = store / "publication.lock"
    _safe_regular_file(path, "selection-publication lock")
    with path.open("a+b") as handle:
        if fcntl is not None:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
        try:
            yield
        finally:
            if fcntl is not None:
                fcntl.flock(handle.fileno(), fcntl.LOCK_UN)


__all__ = (
    "TRANSACTION_ID",
    "_atomic_write",
    "_bounded_file_sha256",
    "_blob_path",
    "_bounded_payload",
    "_canonical_json",
    "_display_json",
    "_lock",
    "_intent_index_path",
    "_prepare_path",
    "_receipts_root",
    "_receipt_path",
    "_sha256_bytes",
    "_sha256_file",
    "_state_path",
    "_successor_bundle_path",
    "_successor_authority_evaluation_context_path",
    "_successor_authority_index_path",
    "_successor_authority_locator_path",
    "_successor_authority_packet_path",
    "_successor_authority_projection_path",
    "_successor_authority_request_context_path",
    "_successor_gate_path",
    "_successor_prepare_index_path",
    "_store_root",
    "_transactions_root",
    "_write_once",
)
