"""Shared cardinality limits for selection-tick producers and validators."""

MAX_WATCH_ENTRIES = 4096
MAX_CHANGE_ENTRIES = 4096
MAX_POLICY_IDS = 64
MAX_CARRIED_WATCH_IDS = 4096
MAX_AUTHORITY_SCOPES = 1024
MAX_PENDING_PUBLICATIONS = 1024
MAX_CALLER_WATCH_PATHS = 4096
MAX_AUTHORITY_PACKETS = 1024
MAX_TASK_PACK_FILES = 4096
MAX_RETIREMENT_FILES = 4096


__all__ = (
    "MAX_AUTHORITY_PACKETS",
    "MAX_AUTHORITY_SCOPES",
    "MAX_CALLER_WATCH_PATHS",
    "MAX_CARRIED_WATCH_IDS",
    "MAX_CHANGE_ENTRIES",
    "MAX_PENDING_PUBLICATIONS",
    "MAX_POLICY_IDS",
    "MAX_RETIREMENT_FILES",
    "MAX_TASK_PACK_FILES",
    "MAX_WATCH_ENTRIES",
)
