from __future__ import annotations

FIELD_ORDER = [
    "기준 GT",
    "비-GT 방향성 문서",
    "주 진행 skill",
    "모델/effort 라우팅",
    "수행한 task",
    "변경한 파일",
    "실행한 검증",
    "validation verdict",
    "progress verdict",
    "progress axes",
    "남은 blocker",
    "다음 task/방향성",
    "완료 여부",
]

STAGE_ORDER = [
    "context",
    "authority",
    "repo_skill_adapter_scan",
    "acceptance",
    "route_plan",
    "validation_scope_plan",
    "validation_set_plan",
    "governance",
    "result_contract",
    "repo_skill_adapter_validate",
    "ledger_append",
    "code_structure_audit",
    "run",
    "qualitative_review",
    "loopback_audit",
    "validation_set_build",
    "visible_increment",
    "repo_skill_gap_analysis",
    "cycle_efficiency_profile",
    "validation_scope_finalize",
    "index_pre_validate",
    "validate",
    "issue",
    "schema_pre_derive",
    "derive",
    "schema_post_derive",
    "index",
    "commit",
    "dashboard",
    "report",
    "closeout_commit",
]
