from __future__ import annotations


# Closed top-level vocabulary emitted by anti-loop-progress-gate-v1 rows. Nested
# gate objects retain their owner-defined contracts and are still privacy checked.
FAMILY_PROGRESS_ROW_FIELDS = frozenset(
    """
    acceptance_reachability_gate
    acceptance_scale
    acceptance_unreachable_under_frozen_config
    acceptance_verifier_not_evaluated
    adapter_contract_unmet
    adapter_hook_demand
    adapter_loaded
    adapter_mandate_gate
    adapter_mandate_required
    adapter_missing_streak
    adapter_registered
    adapter_wiring_defect
    adapter_wiring_gate
    advice_freshness_gate
    advisory_discovery
    artifact_class
    artifact_family
    artifact_id
    artifact_sha256
    attempt_identity
    attempt_identity_version
    attempt_revision_candidate
    attested_only_movement
    authoritative_consumption_allowed
    authoritative_semantic_progress
    blocker_ladder_rung
    blocker_mutation_kind
    blocker_root_family
    blocker_signature
    budget_evaluation_status
    budget_evaluations
    budget_unverified
    c4_user_escalation_backstop_required
    chain_stall_forced_retarget_gate
    changed_vs_previous
    consolidation_budget_evaluation
    consolidation_reduces_goal_distance
    consolidation_streak
    consolidation_streak_cap
    consumer_context_conformance
    correction_of_attempt_identity
    coupled_verifier_gate
    coverage_quality_delta_gate
    coverage_quality_delta_reconciliation_gate
    cumulative_goal_distance_gate
    cumulative_goal_distance_scope_key
    cumulative_goal_distance_stall_streak
    cumulative_goal_distance_stalled
    cumulative_untried_chain_without_quality_delta
    current_output_fingerprint
    cycle_id
    cycle_reachability_gate
    decision_artifact_ref
    decision_consumed_gate_ids
    decision_excluded_gate_ids
    demanded_hooks
    detection_budget_evaluation
    detection_only
    detection_only_streak_cap
    detection_only_streak_for_root_family
    diagnostics_unavailable
    diagnostics_unavailable_gate
    diagnostics_unavailable_streak
    discovery_basis
    disposition_intersection_basis
    domain_adapter
    edge_count
    effective_allowed_dispositions
    effective_count_key
    envelope_thaw_item
    envelope_thaw_item_required
    envelope_thaw_streak
    evidence_class
    evidence_provenance_gate
    event_event_relation_output
    execution_stage_ladder_status
    facet_root_map_applied
    facet_root_map_missing
    facet_root_map_size
    failure_surface_count_key
    failure_surface_stage
    failure_surface_stage_gate
    family_key
    finalization_required
    finalization_state
    finalized_state_cycle_id
    finalized_state_status
    findings
    force_gcov_reconciliation
    force_implementation_cycle
    force_substance_progress
    forced_selected_task
    forced_selected_task_options
    forward_mutation_budget
    forward_mutation_budget_remaining
    forward_mutation_vacuous
    gate_compatibility_results
    goal_terminal_prohibited
    genuine_relation_count
    handoff_contract_version
    hard_stop_required
    harvest_validation_required
    high_water_last_improved_cycle
    high_water_mark
    high_water_vector
    hook_demand_threshold
    hook_supply_required
    hypothesis_exhaustion_seal_candidate
    hypothesis_exhaustion_seal_status
    hypothesis_exhausted
    independent_source_separation_status
    independently_verified_downgraded_fields
    independently_verified_fields
    input_fingerprints
    input_delta_gate
    input_state_fingerprint
    instrumentation_supply_required
    insufficient_evidence_reason
    last_successful_stage
    long_run_launch_required
    local_model_request_count
    marginal_repair
    measurement_budget_evaluation
    measurement_check_ids
    measurement_frontiers_observed
    measurement_goal_productive_allowed
    measurement_progress
    measurement_progress_allowed
    measurement_progress_basis
    measurement_progress_streak_for_root_family
    measurement_progress_streak_for_root_key
    measurement_streak
    measurement_streak_cap
    metric_verifier_not_evaluated
    micro_hardening_count
    not_goal_truth
    not_gold
    not_ready
    observed_delta_class
    offline_scope_unverified
    oracle_metric_validity_gate
    partial_progress_axes_gate
    pass_with_coupled_verifier
    previous_accepted_baseline
    previous_high_water_mark
    previous_output_fingerprint
    primary_metric_gate
    primary_metric_high_water_moved
    primary_metric_stalled
    primary_metric_zero_movement_streak
    producer_attested_fields
    producer_input_ids
    production_lane_identity
    progress_verdict
    produced_domain_delta
    provider_request_count
    provider_scale_dispatch_gate
    quality_delta_policy
    quality_delta_pass
    quality_vector
    recommended_disposition
    registry_idempotent_replay
    registry_label_correction
    registry_state_source
    registry_updated
    relaxation_or_escalation_required
    repo_owned_source_roots
    repo_owned_source_roots_status
    report_body_divergence
    required_gate_ids
    requires_correction_or_terminal
    requires_non_measurement_goal_productive
    residual_gap_policy
    residual_gap_ratio
    root_cause_budget_evaluation
    root_cause_budget_evaluation_status
    root_cause_duplicate_hypotheses
    root_cause_ledger_entries
    root_cause_ledger_state_source
    root_cause_ledger_status
    root_cause_ledger_update_candidate
    root_cause_ledger_updated
    root_cause_unverified_hypotheses
    root_dominant_parameter_key
    root_family_key
    root_key
    same_family_budget_evaluation
    same_family_micro_hardening_count
    same_family_nonsemantic_budget
    same_input_contract_gate
    same_input_contract_violation
    schema_version
    scope_verified
    sealed_blocker_families_state_source
    self_grounded_fields
    semantic_progress
    semantic_signature
    step
    status
    structure_global_invariant_metrics
    structure_high_water_key_scope
    structure_metrics_gate
    substance_delta_gate
    substance_metrics
    supersedes_attempt_identity_candidate
    supersedes_attempt_revision_candidate
    task_correction_class
    terminal_blocked_invalid_due_to_untried_root_cause
    terminal_classification_invalid_for_counting
    terminal_classification_stage_contradiction
    terminal_outcome_changed
    terminal_outcome_family_fallback_applied
    terminal_outcome_family_key
    terminal_outcome_family_previous_count
    terminal_outcome_family_previous_cycle_id
    terminal_outcome_family_source
    terminal_outcome_key
    terminal_self_resolution_gate
    throughput_evidence
    truth_basis
    unreachable_within_cycle
    untried_actionable_root_cause_exists
    untried_promotion_budget
    untried_root_cause_hypotheses
    untried_veto_overridden_by_chain_stall
    unverifiable_acceptance_contract
    vacuous_corrective_gate
    vacuous_untried_attempt_count
    vacuous_untried_streak
    validator_integrity_gate
    verification_axes
    verification_input_ids
    verification_source_separation_gate
    verified_artifact_ids
    """.split()
)


__all__ = ["FAMILY_PROGRESS_ROW_FIELDS"]
